{   scopeName = 'source.relap5';
    fileTypes = (["*.i"] );
    foldingStartMarker = '\{\s*$';
    foldingStopMarker = '^\s*\}';
    patterns = (
        {   name = 'keyword.control.relap5';
            match = '\b(if|while|for|return)\b';
        },
        {
            "match": "#.*",
            "name": "comment.line.number-sign"
        },
        {   name = 'string.quoted.double.relap5';
            begin = '"';
            end = '"';
            patterns = ( 
                {   name = 'constant.character.escape.relap5';
                    match = '\\.';
                }
            );
        },
    );
}